server.port: 8080

management:
  port: 8081

springdoc.swagger-ui.path: /swagger-ui.html

stock-prediction-service:
  random-number:
    min: -100
    max: 100

stock-price-client:
  baseUrl: https://www.randomnumberapi.com/api/v1.0

spring:
  security.user.name: testUser
  security.user.password: S3cret!
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:stock_prediction_db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect